#!/bin/sh -ex

# export NIX_PROFILE="/nix/var/nix/profiles/${USER}"
# export PATH="${NIX_PROFILE}/bin:$PATH"
# export NIX_PATH="nixpkgs=/nix/var/nix/profiles/per-user/${USER}/channels/nixpkgs"

# # The nix installer wants to put things here.
# if [ ! -d /nix ]; then
#     mkdir /nix
# fi

# if [ -d ~/nix-cache ]; then
#     # travis-ci is configured to cache nix-cache.  this holds the nix store
#     # (all our binary artifacts) as well as the nix toolchain itself.
#     install --directory /nix ~/nix-cache
#     # xxx not sure why this is necessary after the above
#     mv ~/nix-cache/* /nix || true
# fi

# if ! type -p nix-build 2>/dev/null; then
#     curl https://nixos.org/nix/install | bash
# fi
