#!/bin/sh -ex

# The Nix build takes place inside a Docker container.  That means we don't
# have any Nix- or build-related installation work to do here.

# We will install https://github.com/praekeltfoundation/docker-ci-deploy to
# help us push the built artifacts to Docker Hub, though.
pip install docker-ci-deploy
