#!/bin/bash -ex
# Copyright Least Authority Enterprises.
# See LICENSE for details.

repo="leastauthority"
microservices="s4-common"

# Build the images.
./leastauthority.com/docker/build.sh

# Log in to Docker Hub so we can push the images.
# https://github.com/moby/moby/issues/6400
yes | docker login \
       --username "$(cat /var/run/secrets/dockerhub/username)" \
       --password "$(cat /var/run/secrets/dockerhub/password)"

# Then tag and push them.
for microservice in ${microservices}; do
    docker tag "${repo}/${microservice}" "${repo}/${microservice}:${DOCKER_TAG}"
    docker push "${repo}/${microservice}:${DOCKER_TAG}"
done

docker logout

echo "Tagged images with ${DOCKER_TAG}"
