#!/bin/bash -e
# Copyright Least Authority Enterprises.
# See LICENSE for details.

microservices="s4-common tahoe-introducer tahoe-storage foolscap-gatherer"

# Build the images.
./leastauthority.com/docker/build.sh

# Log in to Docker Hub so we can push the images.
docker login "$(cat /var/run/secrets/dockerhub/username)" "$(cat /var/run/secrets/dockerhub/password)"

# And push them.
for microservice in ${microservices}; do
    docker push "${microservice}:${DOCKER_TAG}"
done

docker logout

echo "Tagged images with ${DOCKER_TAG}"
