apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: 's4'
data:
  chargebee-site-name: 'leastauthority'
  chargebee-plan-id: 'S4_consumer_iteration_2_beta1_2014-05-27'
  # This must match a Stripe Payment Gateway configured in ChargeBee
  # associated with the same Stripe account as the frontend is configured to
  # use for payment processing.
  chargebee-gateway-account-id: 'gw_2smoc9C8Qz9QjPL1CT'

  stripe-plan-id: 'S4_consumer_iteration_2_beta1_2014-05-27'

  tahoe-introducer-image: 'leastauthority/auto-tahoe-introducer:release-0.0.0'
  tahoe-storage-image: 'leastauthority/auto-tahoe-storage:release-0.0.0'
