#
# This builds an image which runs the S4 subscription convergence loop.
# The anticipated name is <leastauthority/subscription-converger>.
#

FROM leastauthority/base-lae-automation

# Create a user account as whom the subscription manager can run.
ENV SUBSCRIPTION_CONVERGER_USER_NAME="converger"
RUN adduser --disabled-password --gecos "" "${SUBSCRIPTION_CONVERGER_USER_NAME}"

# Run the application with this working directory.
WORKDIR /app/run

# And give it to the user the application will run as.
RUN chown "${SUBSCRIPTION_CONVERGER_USER_NAME}" /app/run

RUN mkdir /app/data && \
    chown "${SUBSCRIPTION_CONVERGER_USER_NAME}":"${SUBSCRIPTION_CONVERGER_USER_NAME}" /app/data

USER "${SUBSCRIPTION_CONVERGER_USER_NAME}"

CMD env && \
    PYTHONPATH="/app/code" \
    /app/env/bin/twist s4-subscription-converger \
    --domain "$(cat /app/k8s_secrets/domain)" \
    --kubernetes-namespace "$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)" \
    --aws-access-key-id-path /app/k8s_secrets/aws.id \
    --aws-secret-access-key-path /app/k8s_secrets/aws.key \
    --introducer-image "${LAE_S4_TAHOE_INTRODUCER_IMAGE}" \
    --storageserver-image "${LAE_S4_TAHOE_STORAGESERVER_IMAGE}" \
    --endpoint http://127.0.0.1:8000/ \
    --k8s-service-account
