#
# This builds an image which runs the S4 subscription convergence loop.
# The anticipated name is <leastauthority/subscription-converger>.
#

FROM leastauthority/base

# Create a user account as whom the subscription manager can run.
ENV SUBSCRIPTION_CONVERGER_USER_NAME="converger"
RUN adduser --disabled-password --gecos "" "${SUBSCRIPTION_CONVERGER_USER_NAME}"

# Run the application with this working directory.
WORKDIR /app/run

# And give it to the user the application will run as.
RUN chown "${SUBSCRIPTION_CONVERGER_USER_NAME}" /app/run

RUN mkdir /app/data && \
    chown "${SUBSCRIPTION_CONVERGER_USER_NAME}":"${SUBSCRIPTION_CONVERGER_USER_NAME}" /app/data

# Install all of the application's Python library requirements.
COPY requirements.txt /app/code/requirements.txt
RUN /app/env/bin/pip install -r /app/code/requirements.txt

# Install the application itself.  This is done as late as possible
# since it is a major impediment to image/layer caching.
COPY . /app/code

# Generate the twisted plugins system cache files
RUN /app/env/bin/twist --help > /dev/null

USER "${SUBSCRIPTION_CONVERGER_USER_NAME}"

CMD env && \
    PYTHONPATH="/app/code" \
    /app/env/bin/twist s4-subscription-converger \
    --aws-access-key-id-path /app/k8s_secrets/aws.id \
    --aws-secret-access-key-path /app/k8s_secrets/aws.key \
    --introducer-image "${LAE_S4_TAHOE_INTRODUCER_IMAGE}" \
    --storageserver-image "${LAE_S4_TAHOE_STORAGESERVER_IMAGE}" \
    --endpoint http://127.0.0.1:8000/ \
    --k8s-service-account
