FROM leastauthority.com/infrastructure

# Facilitate network connections to the application.  It would be nice
# if we could run on the usual port number (443).  However, Docker
# makes that difficult to do without running the whole process as
# root.  For now, the lesser evil is to just use a high-number port
# and make sure the rest of the system is aware of this fact (so that
# the public-facing port 443 is directed to the right container port).
# Perhaps a future version of Docker will let us clean this up.  It's
# more an aesthetic problem than anything else.
EXPOSE 8443

# The command the container will run - the web server.  It would be
# nice if it had some better logging behavior.
CMD mkdir -p /app/data/logs && \
    PYTHONPATH="/app/code" /app/env/bin/python -u /app/code/lae_site/main.py --noredirect=8000 --port=8443 >> /app/data/logs/site.out
