#!/usr/bin/env python

from sys import argv

from twisted.python.filepath import FilePath

_MODES = {
    b"introducer": b"introducer.port",
    b"storage": b"client.port",
}

def main():
    mode, root, port, nodeid, cert, privkey = argv[1:]
    try:
        portfile = _MODES[mode]
    except KeyError:
        raise SystemExit(u"Mode must be one of: {}".format(b"".join(_MODES)))

    root = FilePath(root)

    root.child(b"my_nodeid").setContent(nodeid + b"\n")
    root.child(portfile).setContent(port + b"\n")
    
    private = root.child(b"private")
    private.child(b"node.pem").setContent(cert)
    private.child("node.privkey").setContent(privkey)
