#!/usr/bin/env python

from json import dump
from ConfigParser import SafeConfigParser
from errno import ENOENT

from sys import argv, stdout

from twisted.python.filepath import FilePath

def main():
    introducer_root, storage_root = argv[1:]

    secrets = {}
    secrets.update(record_introducer_secrets(FilePath(introducer_root)))
    secrets.update(record_storage_secrets(FilePath(storage_root)))

    dump(secrets, stdout)

def record_introducer_secrets(root):
    return dict(
        introducer_node_pem=root.descendant((b"private", b"node.pem")).getContent().strip(),
        introducer_nodeid=root.child(b"my_nodeid").getContent().strip(),
        internal_introducer_furl=root.descendant((b"private", b"introducer.furl")).getContent().strip(),
    )

def record_storage_secrets(root):
    privkey_path = root.descendant((b"private", b"node.privkey"))
    try:
        privkey = privkey_path.getContent().strip()
    except IOError as e:
        if ENOENT != e.errno:
            raise
        privkey = None

    config = SafeConfigParser()
    with root.child(b"tahoe.cfg").open() as cfg:
        config.readfp(cfg)
    
    return dict(
        server_node_pem=root.descendant((b"private", b"node.pem")).getContent().strip(),
        server_nodeid=root.child(b"my_nodeid").getContent().strip(),
        server_node_privkey=privkey,
        access_key_id=config.get("storage", "s3.access_key_id"),
        secret_key=root.descendant((b"private", b"s3secret")).getContent().strip(),
        bucket_name=config.get("storage", "s3.bucket"),
        tub_location=config.get('node', 'tub.location'),
    )

if __name__ == '__main__':
    main()
