#!/bin/bash

BUCKET=com.leastauthority.fluentd
read -r -d '' CONFIG<<'EOF'
{
    "LifecycleConfiguration": {
        "Rules": [
            {
                "ID": "delete old log archives",
                "Status": "Enabled",
                "Prefix": "",
                "Expiration": {
                    "Days": 7
                },
                "AbortIncompleteMultipartUpload": {
                    "DaysAfterInitiation": 1
                }
            }
        ]
    }
}
EOF

aws s3api create-bucket --bucket "${BUCKET}"
aws s3api put-bucket-lifecycle --bucket "${BUCKET}" --cli-input-json "${CONFIG}"
