#!/usr/bin/env python

# This simple script tags the local LAE S4 Docker images which currently have
# the `latest` tag with several other interesting tags and pushes them to
# Docker Hub.
#
# Usage:
#
#    $ # ... build some docker images ...
#    $ docker login ..
#    $ deploy-images

from __future__ import print_function

from os import environ
from subprocess import check_output

ORGANIZATION = "leastauthority"
REPOS = [
    "web",
    "grid-router",
    "subscription-manager",
    "subscription-converger",
    "foolscap-gatherer",
    "tahoe-introducer",
    "tahoe-storage",
]


# https://docs.travis-ci.com/user/environment-variables/#Convenience-Variables
def pull_request_branch(environ):
    return environ["TRAVIS_PULL_REQUEST_BRANCH"]


def pull_request_number(environ):
    if environ["TRAVIS_PULL_REQUEST"] == "false":
        return None
    return environ["TRAVIS_PULL_REQUEST"]


def git_branch_name(environ):
    return pull_request_branch(environ) or environ["TRAVIS_BRANCH"]


def main():
    tag_names = filter(None, [
        pull_request_number(environ),
        git_branch_name(environ),
    ])
    print("Tagging with {}".format(" ".join(tag_names)))

    version = check_output(["python", "setup.py", "--version"]).strip()

    deploy = "docker-ci-deploy"
    tag_args = []
    for tag in tag_names:
        tag_args.extend(["--tag", tag])
    args = [
	"--version", version,
        "--version-semver",
    ]
    command = [deploy] + tag_args + args

    for repo in REPOS:
        complete_command = command + ["{}/{}".format(ORGANIZATION, repo)]
        print(complete_command)
        print(check_output(complete_command))


main()
