#!/bin/bash -e

PRODUCTION="useast1.production1-11.leastauthority.com"

HEAD="$(git rev-parse HEAD)"
master="$(git rev-parse master)"

if [ "${HEAD}" != "${master}" ]; then
    echo "Refusing to operate on non-master checkout."
    exit 1
fi

git fetch origin master

APPLY="kubectl --context ${PRODUCTION} apply"
REWRITE="python k8s/rewrite-objects.py --git-tag HEAD"

./k8s/build

sops -d k8s/secrets.production.enc.yaml | \
    ${APPLY} -f -

${APPLY} -f k8s/config.production.yaml

cat k8s/infrastructure/wormhole-server.yaml | \
    ${APPLY} -f -

cat k8s/infrastructure.yaml | \
    ${REWRITE} | \
    ${APPLY} -f -

cat k8s/monitoring/tahoe-lafs-transfer-rate.yaml | \
    ${REWRITE} | \
    ${APPLY} -f -

python k8s/monitoring/grafana-dashboards.py ${PRODUCTION} | \
    ${APPLY} -f -

cat k8s/monitoring/grafana.yaml | \
    ${APPLY} -f -
