#!/usr/bin/env bash

set -e

NAMESPACE="$1"

if [ -z "${NAMESPACE}" ]; then
    NAMESPACE="staging"
fi

APPLY="kubectl --context ${NAMESPACE} apply"
REWRITE="python k8s/rewrite-objects.py --no-volumes --git-tag HEAD"

./k8s/build

cat k8s/infrastructure.yaml | \
    ${REWRITE} | \
    ${APPLY} -f -

sops -d k8s/secrets.staging.enc.yaml | \
    ${APPLY} -f -

${APPLY} -f k8s/config.staging.yaml

${APPLY} -f k8s/infrastructure/wormhole-server.yaml

cat k8s/monitoring/tahoe-lafs-transfer-rate.yaml | \
    ${REWRITE} | \
    ${APPLY} -f -

python k8s/monitoring/grafana-dashboards.py "${NAMESPACE}" | \
    ${APPLY} -f -
